import { useEffect, useState } from "react"
import { fetchAPI } from "../lib/api"

const labels = { article: "文章", encyclopedia: "百科", flashcard: "学习卡片", making_log: "调酒照片", comment: "酒谱评论", community_content: "社区内容", community_comment: "社区评论" }

export default function AdminReportsPage() {
  const [reports, setReports] = useState([]); const [message, setMessage] = useState(""); const headers = { Authorization: `Bearer ${localStorage.getItem("token")}` }
  useEffect(() => { let active = true; fetchAPI("/api/admin/reports", { headers }).then((data) => active && setReports(data.map((item) => ({ ...item, nickname: item.nickname || item.reporter_nickname, email: item.email || item.reporter_email })))).catch((err) => active && setMessage(err.message)); return () => { active = false } }, [])
  async function updateReport(id, status) { await fetchAPI(`/api/admin/reports/${id}`, { method: "PATCH", headers, body: { status } }); setReports((items) => items.map((item) => item.id === id ? { ...item, status } : item)); setMessage(status === "resolved" ? "举报已处理" : "举报已驳回") }
  async function moderate(id, hidden, community) { await fetchAPI(`/api/admin/${community ? "community-comments" : "comments"}/${id}`, { method: "PATCH", headers, body: { is_hidden: hidden } }); setMessage(hidden ? "评论已屏蔽" : "评论已恢复") }
  async function remove(id, community) { if (!window.confirm("确定永久删除这条评论吗？")) return; await fetchAPI(`/api/admin/${community ? "community-comments" : "comments"}/${id}`, { method: "DELETE", headers }); setMessage("评论已删除") }
  return <main className="min-h-screen bg-[var(--color-bg-page)] px-5 pb-24 pt-24 text-[var(--color-text-main)]"><div className="mx-auto max-w-5xl"><p className="mb-3 font-ui text-xs tracking-[0.3em] text-[var(--color-accent)]">MODERATION</p><h1 className="mb-2 font-serif text-4xl">举报处理</h1><p className="mb-8 font-ui text-sm text-[var(--color-text-muted)]">处理违规内容和评论举报。</p>{message && <p className="mb-4 font-ui text-sm text-emerald-400">{message}</p>}{reports.length === 0 ? <p className="border border-[var(--color-border)] bg-[var(--color-bg-card)] p-6 font-ui text-sm text-[var(--color-text-muted)]">暂无举报记录。</p> : <div className="space-y-3">{reports.map((item) => { const isComment = item.target_type === "comment" || item.target_type === "community_comment"; const community = item.target_type === "community_comment"; return <article key={item.id} className="border border-[var(--color-border)] bg-[var(--color-bg-card)] p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-ui text-xs text-[var(--color-accent)]">{labels[item.target_type] || item.target_type} · 举报人：{item.nickname || item.email}</p><h2 className="mt-2 font-serif text-lg">{item.reason}</h2><p className="mt-2 font-ui text-sm text-[var(--color-text-gray)]">{item.detail || "未补充说明"}</p>{isComment && <p className="mt-2 font-ui text-xs text-[var(--color-text-muted)]">评论 ID：{item.target_id}</p>}</div><span className="font-ui text-xs text-[var(--color-text-muted)]">{item.status === "pending" ? "待处理" : item.status === "resolved" ? "已处理" : "已驳回"}</span></div>{item.status === "pending" && <div className="mt-4 flex flex-wrap gap-2">{isComment && <><button type="button" onClick={() => moderate(item.target_id, true, community)} className="border border-amber-400/50 px-4 py-2 font-ui text-sm text-amber-300">屏蔽评论</button><button type="button" onClick={() => remove(item.target_id, community)} className="border border-red-400/50 px-4 py-2 font-ui text-sm text-red-300">删除评论</button></>}<button type="button" onClick={() => updateReport(item.id, "resolved")} className="bg-[var(--color-accent)] px-4 py-2 font-ui text-sm text-[var(--color-bg-page)]">标记已处理</button><button type="button" onClick={() => updateReport(item.id, "dismissed")} className="border border-[var(--color-border)] px-4 py-2 font-ui text-sm text-[var(--color-text-gray)]">驳回举报</button></div>}</article> })}</div>}</div></main>
}
