import { useEffect, useState } from "react"
import { ArrowLeft, Flame, MessageCircle, ThumbsUp } from "lucide-react"
import { Link } from "react-router-dom"
import { fetchAPI } from "../lib/api"

export default function CommunityPopularPage() {
  const [items, setItems] = useState(null); const [error, setError] = useState("")
  useEffect(() => { fetchAPI("/api/community/popular").then(setItems).catch((e) => setError(e.message)) }, [])
  if (error) return <main className="min-h-screen px-5 pt-32 text-center font-ui text-sm text-red-300">{error}</main>
  if (!items) return <main className="flex min-h-screen items-center justify-center pt-16 font-ui text-sm text-[var(--color-text-muted)]">热榜加载中...</main>
  return <main className="min-h-screen bg-[var(--color-bg-page)] px-5 pb-24 pt-24 text-[var(--color-text-main)]"><div className="mx-auto max-w-4xl"><Link to="/community" className="mb-10 inline-flex items-center gap-2 font-ui text-sm text-[var(--color-text-gray)] hover:text-[var(--color-accent)]"><ArrowLeft size={16} />返回公开内容</Link><header className="mb-10"><p className="mb-3 flex items-center gap-2 font-ui text-xs tracking-[0.3em] text-[var(--color-accent)]"><Flame size={15} />COMMUNITY HOT</p><h1 className="font-serif text-4xl">社区热榜</h1><p className="mt-3 font-ui text-sm text-[var(--color-text-muted)]">根据点赞和评论互动量排序。</p></header><div className="space-y-3">{items.map((item, index) => <Link key={item.id} to={`/community/${item.id}`} className="flex items-start gap-4 border border-[var(--color-border)] bg-[var(--color-bg-card)] p-5 transition-colors hover:border-[var(--color-accent)]"><span className={`w-7 shrink-0 font-serif text-2xl ${index < 3 ? "text-[var(--color-accent)]" : "text-[var(--color-text-muted)]"}`}>{index + 1}</span><div className="min-w-0 flex-1"><p className="font-ui text-xs text-[var(--color-accent)]">{item.content_type === "article" ? "文章" : item.content_type === "flashcard" ? "学习卡片" : "百科词条"}</p><h2 className="mt-1 font-serif text-xl">{item.title}</h2><p className="mt-2 line-clamp-2 font-ui text-sm leading-6 text-[var(--color-text-gray)]">{item.summary || "社区贡献内容"}</p><p className="mt-3 flex items-center gap-4 font-ui text-xs text-[var(--color-text-muted)]"><span className="inline-flex items-center gap-1"><ThumbsUp size={13} />{item.like_count || 0}</span><span className="inline-flex items-center gap-1"><MessageCircle size={13} />{item.comment_count || 0}</span></p></div></Link>)}</div>{items.length === 0 && <div className="border border-[var(--color-border)] bg-[var(--color-bg-card)] p-12 text-center font-ui text-sm text-[var(--color-text-muted)]">暂时还没有热门内容</div>}</div></main>
}
